name: Changeset PR Comment
description: Add a comment to a PR if a changeset is not present

inputs:
  message:
    description: The message to comment on the PR
    default: 'Hey! Remember to add a changeset with `pnpm changeset add` to describe your changes for versioning.'

runs:
  using: composite
  steps:
    - name: Check required tools
      shell: bash
      run: |
        command -v gh >/dev/null 2>&1 || {
          echo "GitHub CLI (gh) is required"
          exit 1
        }

        command -v jq >/dev/null 2>&1 || {
          echo "jq is required"
          exit 1
        }

    - name: Check if a comment already exists
      id: check_comment
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        MESSAGE: ${{ inputs.message }}
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "pr_number=$PR_NUMBER" >> "$GITHUB_ENV"

        COMMENTS=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json comments --jq ".comments[] | select(.body | contains(\"${MESSAGE}\")) | .id")

        if [ -n "$COMMENTS" ]; then
          echo "comment_exists=true" >> "$GITHUB_ENV"
        else
          echo "comment_exists=false" >> "$GITHUB_ENV"
        fi

    - name: Add comment if no comment posted
      if: env.comment_exists == 'false'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        MESSAGE: ${{ inputs.message }}
      run: |
        gh pr comment "$pr_number" --repo "$GITHUB_REPOSITORY" --body "$MESSAGE"
