on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-slim
      timeout-minutes:
        required: false
        type: number
        default: 10
        description: Timeout in minutes for each job.

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  comment:
    if: github.actor != 'dependabot[bot]'

    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}

    permissions:
      pull-requests: write

    steps:
      - name: Post comment
        uses: 4mbl/actions/changeset/pr-comment@3503abea552212c9895cf51a7538f69137d421e2 # v1
