on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      timeout-minutes:
        required: false
        type: number
        default: 10
        description: Timeout in minutes for each step.
      disable-steps:
        required: false
        type: string
        default: '[""]'
    secrets:
      TURBO_TOKEN:
        description: Access token to a Turborepo compatible Remote Cache. You need to configure Turbo on your repo and call `turbo` on your `package.json` scripts for this to have any effect. You also need to pass TURBO_TEAM secret to this workflow.
        required: false
      TURBO_TEAM:
        description: Turborepo team name. You also need to pass TURBO_TOKEN secret to this workflow.
        required: false

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # main
        with:
          cache: true
          run_install: true

  typecheck:
    name: Typecheck
    needs: setup
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: ${{ !contains(fromJson(inputs.disable-steps), 'typecheck') }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # main
        with:
          cache: true
          run_install: true

      - run: pnpm run --if-present typecheck

  format:
    name: Format
    needs: setup
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: ${{ !contains(fromJson(inputs.disable-steps), 'format') }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # main
        with:
          cache: true
          run_install: true

      - run: pnpm run --if-present format:check

  lint:
    name: Lint
    needs: setup
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: ${{ !contains(fromJson(inputs.disable-steps), 'lint') }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # main
        with:
          cache: true
          run_install: true

      - run: pnpm run --if-present lint

  build:
    name: Build
    needs: setup
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: ${{ !contains(fromJson(inputs.disable-steps), 'build') }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # main
        with:
          cache: true
          run_install: true

      - run: pnpm run --if-present build

  test:
    name: Test
    needs: setup
    runs-on: ${{ inputs.os }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    if: ${{ !contains(fromJson(inputs.disable-steps), 'test') }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: package.json

      - uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c # main
        with:
          cache: true
          run_install: true

      - run: pnpm run --if-present test

  results:
    name: Report results
    runs-on: ${{ inputs.os }}
    needs:
      - setup
      - typecheck
      - format
      - lint
      - build
      - test
    if: always()
    steps:
      - name: Evaluate results
        run: |
          results=(
            "${{ needs.setup.result }}"
            "${{ needs.typecheck.result }}"
            "${{ needs.format.result }}"
            "${{ needs.lint.result }}"
            "${{ needs.build.result }}"
            "${{ needs.test.result }}"
          )

          for result in "${results[@]}"; do
            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
              echo "CI failed due to job result: $result"
              exit 1
            fi
          done

          echo "All required jobs succeeded or were skipped"
